services:
  - type: web
    name: edubot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
